// flow-typed signature: 8a9e9c78cfd8b55aa1315dc4c480bef3
// flow-typed version: <<STUB>>/victory-chart_v^25.1.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'victory-chart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'victory-chart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'victory-chart/dist/victory-chart' {
  declare module.exports: any;
}

declare module 'victory-chart/dist/victory-chart.min' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/addons/victory-brush-line' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/brush-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/create-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/cursor-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/selection-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-brush-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-cursor-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-selection-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-voronoi-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/victory-zoom-container' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/voronoi-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/containers/zoom-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-area/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-area/victory-area' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-axis/victory-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-bar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-bar/victory-bar' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-candlestick/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-candlestick/victory-candlestick' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-chart/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-chart/victory-chart' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-errorbar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-errorbar/victory-errorbar' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-group/victory-group' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-line/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-line/victory-line' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-polar-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-polar-axis/victory-polar-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-scatter/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-scatter/victory-scatter' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-stack/victory-stack' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-voronoi/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/es/components/victory-voronoi/victory-voronoi' {
  declare module.exports: any;
}

declare module 'victory-chart/es/helpers/axis' {
  declare module.exports: any;
}

declare module 'victory-chart/es/helpers/common-props' {
  declare module.exports: any;
}

declare module 'victory-chart/es/helpers/wrapper' {
  declare module.exports: any;
}

declare module 'victory-chart/es/index' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/addons/victory-brush-line' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/brush-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/create-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/cursor-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/selection-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-brush-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-cursor-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-selection-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-voronoi-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/victory-zoom-container' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/voronoi-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/containers/zoom-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-area/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-area/victory-area' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-axis/victory-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-bar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-bar/victory-bar' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-candlestick/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-candlestick/victory-candlestick' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-chart/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-chart/victory-chart' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-errorbar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-errorbar/victory-errorbar' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-group/victory-group' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-line/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-line/victory-line' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-polar-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-polar-axis/victory-polar-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-scatter/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-scatter/victory-scatter' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-stack/victory-stack' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-voronoi/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/components/victory-voronoi/victory-voronoi' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/helpers/axis' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/helpers/common-props' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/helpers/wrapper' {
  declare module.exports: any;
}

declare module 'victory-chart/lib/index' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/addons/victory-brush-line' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/brush-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/create-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/cursor-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/selection-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-brush-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-cursor-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-selection-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-voronoi-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/victory-zoom-container' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/voronoi-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/containers/zoom-helpers' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-area/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-area/victory-area' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-axis/victory-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-bar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-bar/victory-bar' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-candlestick/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-candlestick/victory-candlestick' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-chart/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-chart/victory-chart' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-errorbar/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-errorbar/victory-errorbar' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-group/victory-group' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-line/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-line/victory-line' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-polar-axis/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-polar-axis/victory-polar-axis' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-scatter/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-scatter/victory-scatter' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-stack/victory-stack' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-voronoi/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-chart/src/components/victory-voronoi/victory-voronoi' {
  declare module.exports: any;
}

declare module 'victory-chart/src/helpers/axis' {
  declare module.exports: any;
}

declare module 'victory-chart/src/helpers/common-props' {
  declare module.exports: any;
}

declare module 'victory-chart/src/helpers/wrapper' {
  declare module.exports: any;
}

declare module 'victory-chart/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'victory-chart/dist/victory-chart.js' {
  declare module.exports: $Exports<'victory-chart/dist/victory-chart'>;
}
declare module 'victory-chart/dist/victory-chart.min.js' {
  declare module.exports: $Exports<'victory-chart/dist/victory-chart.min'>;
}
declare module 'victory-chart/es/components/addons/victory-brush-line.js' {
  declare module.exports: $Exports<'victory-chart/es/components/addons/victory-brush-line'>;
}
declare module 'victory-chart/es/components/containers/brush-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/brush-helpers'>;
}
declare module 'victory-chart/es/components/containers/create-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/create-container'>;
}
declare module 'victory-chart/es/components/containers/cursor-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/cursor-helpers'>;
}
declare module 'victory-chart/es/components/containers/selection-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/selection-helpers'>;
}
declare module 'victory-chart/es/components/containers/victory-brush-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-brush-container'>;
}
declare module 'victory-chart/es/components/containers/victory-cursor-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-cursor-container'>;
}
declare module 'victory-chart/es/components/containers/victory-selection-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-selection-container'>;
}
declare module 'victory-chart/es/components/containers/victory-voronoi-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-voronoi-container'>;
}
declare module 'victory-chart/es/components/containers/victory-zoom-container.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/victory-zoom-container'>;
}
declare module 'victory-chart/es/components/containers/voronoi-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/voronoi-helpers'>;
}
declare module 'victory-chart/es/components/containers/zoom-helpers.js' {
  declare module.exports: $Exports<'victory-chart/es/components/containers/zoom-helpers'>;
}
declare module 'victory-chart/es/components/victory-area/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-area/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-area/victory-area.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-area/victory-area'>;
}
declare module 'victory-chart/es/components/victory-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-axis/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-axis/victory-axis.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-axis/victory-axis'>;
}
declare module 'victory-chart/es/components/victory-bar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-bar/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-bar/victory-bar.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-bar/victory-bar'>;
}
declare module 'victory-chart/es/components/victory-candlestick/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-candlestick/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-candlestick/victory-candlestick.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-candlestick/victory-candlestick'>;
}
declare module 'victory-chart/es/components/victory-chart/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-chart/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-chart/victory-chart.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-chart/victory-chart'>;
}
declare module 'victory-chart/es/components/victory-errorbar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-errorbar/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-errorbar/victory-errorbar.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-errorbar/victory-errorbar'>;
}
declare module 'victory-chart/es/components/victory-group/victory-group.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-group/victory-group'>;
}
declare module 'victory-chart/es/components/victory-line/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-line/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-line/victory-line.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-line/victory-line'>;
}
declare module 'victory-chart/es/components/victory-polar-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-polar-axis/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-polar-axis/victory-polar-axis.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-polar-axis/victory-polar-axis'>;
}
declare module 'victory-chart/es/components/victory-scatter/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-scatter/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-scatter/victory-scatter.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-scatter/victory-scatter'>;
}
declare module 'victory-chart/es/components/victory-stack/victory-stack.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-stack/victory-stack'>;
}
declare module 'victory-chart/es/components/victory-voronoi/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-voronoi/helper-methods'>;
}
declare module 'victory-chart/es/components/victory-voronoi/victory-voronoi.js' {
  declare module.exports: $Exports<'victory-chart/es/components/victory-voronoi/victory-voronoi'>;
}
declare module 'victory-chart/es/helpers/axis.js' {
  declare module.exports: $Exports<'victory-chart/es/helpers/axis'>;
}
declare module 'victory-chart/es/helpers/common-props.js' {
  declare module.exports: $Exports<'victory-chart/es/helpers/common-props'>;
}
declare module 'victory-chart/es/helpers/wrapper.js' {
  declare module.exports: $Exports<'victory-chart/es/helpers/wrapper'>;
}
declare module 'victory-chart/es/index.js' {
  declare module.exports: $Exports<'victory-chart/es/index'>;
}
declare module 'victory-chart/lib/components/addons/victory-brush-line.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/addons/victory-brush-line'>;
}
declare module 'victory-chart/lib/components/containers/brush-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/brush-helpers'>;
}
declare module 'victory-chart/lib/components/containers/create-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/create-container'>;
}
declare module 'victory-chart/lib/components/containers/cursor-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/cursor-helpers'>;
}
declare module 'victory-chart/lib/components/containers/selection-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/selection-helpers'>;
}
declare module 'victory-chart/lib/components/containers/victory-brush-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-brush-container'>;
}
declare module 'victory-chart/lib/components/containers/victory-cursor-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-cursor-container'>;
}
declare module 'victory-chart/lib/components/containers/victory-selection-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-selection-container'>;
}
declare module 'victory-chart/lib/components/containers/victory-voronoi-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-voronoi-container'>;
}
declare module 'victory-chart/lib/components/containers/victory-zoom-container.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/victory-zoom-container'>;
}
declare module 'victory-chart/lib/components/containers/voronoi-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/voronoi-helpers'>;
}
declare module 'victory-chart/lib/components/containers/zoom-helpers.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/containers/zoom-helpers'>;
}
declare module 'victory-chart/lib/components/victory-area/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-area/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-area/victory-area.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-area/victory-area'>;
}
declare module 'victory-chart/lib/components/victory-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-axis/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-axis/victory-axis.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-axis/victory-axis'>;
}
declare module 'victory-chart/lib/components/victory-bar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-bar/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-bar/victory-bar.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-bar/victory-bar'>;
}
declare module 'victory-chart/lib/components/victory-candlestick/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-candlestick/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-candlestick/victory-candlestick.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-candlestick/victory-candlestick'>;
}
declare module 'victory-chart/lib/components/victory-chart/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-chart/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-chart/victory-chart.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-chart/victory-chart'>;
}
declare module 'victory-chart/lib/components/victory-errorbar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-errorbar/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-errorbar/victory-errorbar.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-errorbar/victory-errorbar'>;
}
declare module 'victory-chart/lib/components/victory-group/victory-group.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-group/victory-group'>;
}
declare module 'victory-chart/lib/components/victory-line/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-line/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-line/victory-line.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-line/victory-line'>;
}
declare module 'victory-chart/lib/components/victory-polar-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-polar-axis/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-polar-axis/victory-polar-axis.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-polar-axis/victory-polar-axis'>;
}
declare module 'victory-chart/lib/components/victory-scatter/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-scatter/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-scatter/victory-scatter.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-scatter/victory-scatter'>;
}
declare module 'victory-chart/lib/components/victory-stack/victory-stack.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-stack/victory-stack'>;
}
declare module 'victory-chart/lib/components/victory-voronoi/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-voronoi/helper-methods'>;
}
declare module 'victory-chart/lib/components/victory-voronoi/victory-voronoi.js' {
  declare module.exports: $Exports<'victory-chart/lib/components/victory-voronoi/victory-voronoi'>;
}
declare module 'victory-chart/lib/helpers/axis.js' {
  declare module.exports: $Exports<'victory-chart/lib/helpers/axis'>;
}
declare module 'victory-chart/lib/helpers/common-props.js' {
  declare module.exports: $Exports<'victory-chart/lib/helpers/common-props'>;
}
declare module 'victory-chart/lib/helpers/wrapper.js' {
  declare module.exports: $Exports<'victory-chart/lib/helpers/wrapper'>;
}
declare module 'victory-chart/lib/index.js' {
  declare module.exports: $Exports<'victory-chart/lib/index'>;
}
declare module 'victory-chart/src/components/addons/victory-brush-line.js' {
  declare module.exports: $Exports<'victory-chart/src/components/addons/victory-brush-line'>;
}
declare module 'victory-chart/src/components/containers/brush-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/brush-helpers'>;
}
declare module 'victory-chart/src/components/containers/create-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/create-container'>;
}
declare module 'victory-chart/src/components/containers/cursor-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/cursor-helpers'>;
}
declare module 'victory-chart/src/components/containers/selection-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/selection-helpers'>;
}
declare module 'victory-chart/src/components/containers/victory-brush-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-brush-container'>;
}
declare module 'victory-chart/src/components/containers/victory-cursor-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-cursor-container'>;
}
declare module 'victory-chart/src/components/containers/victory-selection-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-selection-container'>;
}
declare module 'victory-chart/src/components/containers/victory-voronoi-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-voronoi-container'>;
}
declare module 'victory-chart/src/components/containers/victory-zoom-container.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/victory-zoom-container'>;
}
declare module 'victory-chart/src/components/containers/voronoi-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/voronoi-helpers'>;
}
declare module 'victory-chart/src/components/containers/zoom-helpers.js' {
  declare module.exports: $Exports<'victory-chart/src/components/containers/zoom-helpers'>;
}
declare module 'victory-chart/src/components/victory-area/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-area/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-area/victory-area.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-area/victory-area'>;
}
declare module 'victory-chart/src/components/victory-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-axis/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-axis/victory-axis.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-axis/victory-axis'>;
}
declare module 'victory-chart/src/components/victory-bar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-bar/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-bar/victory-bar.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-bar/victory-bar'>;
}
declare module 'victory-chart/src/components/victory-candlestick/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-candlestick/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-candlestick/victory-candlestick.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-candlestick/victory-candlestick'>;
}
declare module 'victory-chart/src/components/victory-chart/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-chart/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-chart/victory-chart.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-chart/victory-chart'>;
}
declare module 'victory-chart/src/components/victory-errorbar/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-errorbar/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-errorbar/victory-errorbar.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-errorbar/victory-errorbar'>;
}
declare module 'victory-chart/src/components/victory-group/victory-group.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-group/victory-group'>;
}
declare module 'victory-chart/src/components/victory-line/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-line/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-line/victory-line.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-line/victory-line'>;
}
declare module 'victory-chart/src/components/victory-polar-axis/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-polar-axis/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-polar-axis/victory-polar-axis.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-polar-axis/victory-polar-axis'>;
}
declare module 'victory-chart/src/components/victory-scatter/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-scatter/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-scatter/victory-scatter.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-scatter/victory-scatter'>;
}
declare module 'victory-chart/src/components/victory-stack/victory-stack.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-stack/victory-stack'>;
}
declare module 'victory-chart/src/components/victory-voronoi/helper-methods.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-voronoi/helper-methods'>;
}
declare module 'victory-chart/src/components/victory-voronoi/victory-voronoi.js' {
  declare module.exports: $Exports<'victory-chart/src/components/victory-voronoi/victory-voronoi'>;
}
declare module 'victory-chart/src/helpers/axis.js' {
  declare module.exports: $Exports<'victory-chart/src/helpers/axis'>;
}
declare module 'victory-chart/src/helpers/common-props.js' {
  declare module.exports: $Exports<'victory-chart/src/helpers/common-props'>;
}
declare module 'victory-chart/src/helpers/wrapper.js' {
  declare module.exports: $Exports<'victory-chart/src/helpers/wrapper'>;
}
declare module 'victory-chart/src/index.js' {
  declare module.exports: $Exports<'victory-chart/src/index'>;
}
