// flow-typed signature: d6da190621b2bb3b0d48cba17e7d8998
// flow-typed version: <<STUB>>/victory-core_v^21.0.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'victory-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'victory-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'victory-core/dist/victory-core' {
  declare module.exports: any;
}

declare module 'victory-core/dist/victory-core.min' {
  declare module.exports: any;
}

declare module 'victory-core/es/index' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-animation/util' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-animation/victory-animation' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-clip-container/victory-clip-container' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-container/victory-container' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-label/victory-label' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-legend/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-legend/victory-legend' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-portal/portal' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-portal/victory-portal' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/arc' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/area' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/axis' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/bar' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/border' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/candle' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/circle' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/clip-path' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/common-props' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/curve' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/error-bar' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/flyout' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/helpers' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/line' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/path-helpers' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/path' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/point' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/rect' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/slice' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/text' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/tspan' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-primitives/voronoi' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-shared-events/victory-shared-events' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-theme/grayscale' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-theme/material' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-theme/victory-theme' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-tooltip/victory-tooltip' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-transition/victory-transition' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/add-events' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/collection' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/data' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/default-transitions' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/domain' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/events' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/helpers' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/immutable' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/label-helpers' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/log' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/prop-types' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/scale' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/selection' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/style' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/textsize' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/timer' {
  declare module.exports: any;
}

declare module 'victory-core/es/victory-util/transitions' {
  declare module.exports: any;
}

declare module 'victory-core/lib/index' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-animation/util' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-animation/victory-animation' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-clip-container/victory-clip-container' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-container/victory-container' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-label/victory-label' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-legend/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-legend/victory-legend' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-portal/portal' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-portal/victory-portal' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/arc' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/area' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/axis' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/bar' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/border' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/candle' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/circle' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/clip-path' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/common-props' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/curve' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/error-bar' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/flyout' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/helpers' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/line' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/path-helpers' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/path' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/point' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/rect' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/slice' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/text' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/tspan' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-primitives/voronoi' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-shared-events/victory-shared-events' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-theme/grayscale' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-theme/material' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-theme/victory-theme' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-tooltip/victory-tooltip' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-transition/victory-transition' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/add-events' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/collection' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/data' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/default-transitions' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/domain' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/events' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/helpers' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/immutable' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/label-helpers' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/log' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/prop-types' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/scale' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/selection' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/style' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/textsize' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/timer' {
  declare module.exports: any;
}

declare module 'victory-core/lib/victory-util/transitions' {
  declare module.exports: any;
}

declare module 'victory-core/src/index' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-animation/util' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-animation/victory-animation' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-clip-container/victory-clip-container' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-container/victory-container' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-label/victory-label' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-legend/helper-methods' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-legend/victory-legend' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-portal/portal' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-portal/victory-portal' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/arc' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/area' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/axis' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/bar' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/border' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/candle' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/circle' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/clip-path' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/common-props' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/curve' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/error-bar' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/flyout' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/helpers' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/line' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/path-helpers' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/path' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/point' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/rect' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/slice' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/text' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/tspan' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-primitives/voronoi' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-shared-events/victory-shared-events' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-theme/grayscale' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-theme/material' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-theme/victory-theme' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-tooltip/victory-tooltip' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-transition/victory-transition' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/add-events' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/collection' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/data' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/default-transitions' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/domain' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/events' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/helpers' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/immutable' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/label-helpers' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/log' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/prop-types' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/scale' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/selection' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/style' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/textsize' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/timer' {
  declare module.exports: any;
}

declare module 'victory-core/src/victory-util/transitions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'victory-core/dist/victory-core.js' {
  declare module.exports: $Exports<'victory-core/dist/victory-core'>;
}
declare module 'victory-core/dist/victory-core.min.js' {
  declare module.exports: $Exports<'victory-core/dist/victory-core.min'>;
}
declare module 'victory-core/es/index.js' {
  declare module.exports: $Exports<'victory-core/es/index'>;
}
declare module 'victory-core/es/victory-animation/util.js' {
  declare module.exports: $Exports<'victory-core/es/victory-animation/util'>;
}
declare module 'victory-core/es/victory-animation/victory-animation.js' {
  declare module.exports: $Exports<'victory-core/es/victory-animation/victory-animation'>;
}
declare module 'victory-core/es/victory-clip-container/victory-clip-container.js' {
  declare module.exports: $Exports<'victory-core/es/victory-clip-container/victory-clip-container'>;
}
declare module 'victory-core/es/victory-container/victory-container.js' {
  declare module.exports: $Exports<'victory-core/es/victory-container/victory-container'>;
}
declare module 'victory-core/es/victory-label/victory-label.js' {
  declare module.exports: $Exports<'victory-core/es/victory-label/victory-label'>;
}
declare module 'victory-core/es/victory-legend/helper-methods.js' {
  declare module.exports: $Exports<'victory-core/es/victory-legend/helper-methods'>;
}
declare module 'victory-core/es/victory-legend/victory-legend.js' {
  declare module.exports: $Exports<'victory-core/es/victory-legend/victory-legend'>;
}
declare module 'victory-core/es/victory-portal/portal.js' {
  declare module.exports: $Exports<'victory-core/es/victory-portal/portal'>;
}
declare module 'victory-core/es/victory-portal/victory-portal.js' {
  declare module.exports: $Exports<'victory-core/es/victory-portal/victory-portal'>;
}
declare module 'victory-core/es/victory-primitives/arc.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/arc'>;
}
declare module 'victory-core/es/victory-primitives/area.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/area'>;
}
declare module 'victory-core/es/victory-primitives/axis.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/axis'>;
}
declare module 'victory-core/es/victory-primitives/bar.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/bar'>;
}
declare module 'victory-core/es/victory-primitives/border.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/border'>;
}
declare module 'victory-core/es/victory-primitives/candle.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/candle'>;
}
declare module 'victory-core/es/victory-primitives/circle.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/circle'>;
}
declare module 'victory-core/es/victory-primitives/clip-path.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/clip-path'>;
}
declare module 'victory-core/es/victory-primitives/common-props.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/common-props'>;
}
declare module 'victory-core/es/victory-primitives/curve.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/curve'>;
}
declare module 'victory-core/es/victory-primitives/error-bar.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/error-bar'>;
}
declare module 'victory-core/es/victory-primitives/flyout.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/flyout'>;
}
declare module 'victory-core/es/victory-primitives/helpers.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/helpers'>;
}
declare module 'victory-core/es/victory-primitives/line.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/line'>;
}
declare module 'victory-core/es/victory-primitives/path-helpers.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/path-helpers'>;
}
declare module 'victory-core/es/victory-primitives/path.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/path'>;
}
declare module 'victory-core/es/victory-primitives/point.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/point'>;
}
declare module 'victory-core/es/victory-primitives/rect.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/rect'>;
}
declare module 'victory-core/es/victory-primitives/slice.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/slice'>;
}
declare module 'victory-core/es/victory-primitives/text.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/text'>;
}
declare module 'victory-core/es/victory-primitives/tspan.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/tspan'>;
}
declare module 'victory-core/es/victory-primitives/voronoi.js' {
  declare module.exports: $Exports<'victory-core/es/victory-primitives/voronoi'>;
}
declare module 'victory-core/es/victory-shared-events/victory-shared-events.js' {
  declare module.exports: $Exports<'victory-core/es/victory-shared-events/victory-shared-events'>;
}
declare module 'victory-core/es/victory-theme/grayscale.js' {
  declare module.exports: $Exports<'victory-core/es/victory-theme/grayscale'>;
}
declare module 'victory-core/es/victory-theme/material.js' {
  declare module.exports: $Exports<'victory-core/es/victory-theme/material'>;
}
declare module 'victory-core/es/victory-theme/victory-theme.js' {
  declare module.exports: $Exports<'victory-core/es/victory-theme/victory-theme'>;
}
declare module 'victory-core/es/victory-tooltip/victory-tooltip.js' {
  declare module.exports: $Exports<'victory-core/es/victory-tooltip/victory-tooltip'>;
}
declare module 'victory-core/es/victory-transition/victory-transition.js' {
  declare module.exports: $Exports<'victory-core/es/victory-transition/victory-transition'>;
}
declare module 'victory-core/es/victory-util/add-events.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/add-events'>;
}
declare module 'victory-core/es/victory-util/collection.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/collection'>;
}
declare module 'victory-core/es/victory-util/data.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/data'>;
}
declare module 'victory-core/es/victory-util/default-transitions.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/default-transitions'>;
}
declare module 'victory-core/es/victory-util/domain.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/domain'>;
}
declare module 'victory-core/es/victory-util/events.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/events'>;
}
declare module 'victory-core/es/victory-util/helpers.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/helpers'>;
}
declare module 'victory-core/es/victory-util/immutable.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/immutable'>;
}
declare module 'victory-core/es/victory-util/label-helpers.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/label-helpers'>;
}
declare module 'victory-core/es/victory-util/log.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/log'>;
}
declare module 'victory-core/es/victory-util/prop-types.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/prop-types'>;
}
declare module 'victory-core/es/victory-util/scale.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/scale'>;
}
declare module 'victory-core/es/victory-util/selection.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/selection'>;
}
declare module 'victory-core/es/victory-util/style.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/style'>;
}
declare module 'victory-core/es/victory-util/textsize.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/textsize'>;
}
declare module 'victory-core/es/victory-util/timer.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/timer'>;
}
declare module 'victory-core/es/victory-util/transitions.js' {
  declare module.exports: $Exports<'victory-core/es/victory-util/transitions'>;
}
declare module 'victory-core/lib/index.js' {
  declare module.exports: $Exports<'victory-core/lib/index'>;
}
declare module 'victory-core/lib/victory-animation/util.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-animation/util'>;
}
declare module 'victory-core/lib/victory-animation/victory-animation.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-animation/victory-animation'>;
}
declare module 'victory-core/lib/victory-clip-container/victory-clip-container.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-clip-container/victory-clip-container'>;
}
declare module 'victory-core/lib/victory-container/victory-container.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-container/victory-container'>;
}
declare module 'victory-core/lib/victory-label/victory-label.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-label/victory-label'>;
}
declare module 'victory-core/lib/victory-legend/helper-methods.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-legend/helper-methods'>;
}
declare module 'victory-core/lib/victory-legend/victory-legend.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-legend/victory-legend'>;
}
declare module 'victory-core/lib/victory-portal/portal.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-portal/portal'>;
}
declare module 'victory-core/lib/victory-portal/victory-portal.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-portal/victory-portal'>;
}
declare module 'victory-core/lib/victory-primitives/arc.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/arc'>;
}
declare module 'victory-core/lib/victory-primitives/area.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/area'>;
}
declare module 'victory-core/lib/victory-primitives/axis.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/axis'>;
}
declare module 'victory-core/lib/victory-primitives/bar.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/bar'>;
}
declare module 'victory-core/lib/victory-primitives/border.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/border'>;
}
declare module 'victory-core/lib/victory-primitives/candle.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/candle'>;
}
declare module 'victory-core/lib/victory-primitives/circle.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/circle'>;
}
declare module 'victory-core/lib/victory-primitives/clip-path.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/clip-path'>;
}
declare module 'victory-core/lib/victory-primitives/common-props.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/common-props'>;
}
declare module 'victory-core/lib/victory-primitives/curve.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/curve'>;
}
declare module 'victory-core/lib/victory-primitives/error-bar.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/error-bar'>;
}
declare module 'victory-core/lib/victory-primitives/flyout.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/flyout'>;
}
declare module 'victory-core/lib/victory-primitives/helpers.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/helpers'>;
}
declare module 'victory-core/lib/victory-primitives/line.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/line'>;
}
declare module 'victory-core/lib/victory-primitives/path-helpers.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/path-helpers'>;
}
declare module 'victory-core/lib/victory-primitives/path.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/path'>;
}
declare module 'victory-core/lib/victory-primitives/point.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/point'>;
}
declare module 'victory-core/lib/victory-primitives/rect.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/rect'>;
}
declare module 'victory-core/lib/victory-primitives/slice.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/slice'>;
}
declare module 'victory-core/lib/victory-primitives/text.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/text'>;
}
declare module 'victory-core/lib/victory-primitives/tspan.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/tspan'>;
}
declare module 'victory-core/lib/victory-primitives/voronoi.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-primitives/voronoi'>;
}
declare module 'victory-core/lib/victory-shared-events/victory-shared-events.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-shared-events/victory-shared-events'>;
}
declare module 'victory-core/lib/victory-theme/grayscale.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-theme/grayscale'>;
}
declare module 'victory-core/lib/victory-theme/material.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-theme/material'>;
}
declare module 'victory-core/lib/victory-theme/victory-theme.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-theme/victory-theme'>;
}
declare module 'victory-core/lib/victory-tooltip/victory-tooltip.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-tooltip/victory-tooltip'>;
}
declare module 'victory-core/lib/victory-transition/victory-transition.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-transition/victory-transition'>;
}
declare module 'victory-core/lib/victory-util/add-events.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/add-events'>;
}
declare module 'victory-core/lib/victory-util/collection.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/collection'>;
}
declare module 'victory-core/lib/victory-util/data.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/data'>;
}
declare module 'victory-core/lib/victory-util/default-transitions.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/default-transitions'>;
}
declare module 'victory-core/lib/victory-util/domain.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/domain'>;
}
declare module 'victory-core/lib/victory-util/events.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/events'>;
}
declare module 'victory-core/lib/victory-util/helpers.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/helpers'>;
}
declare module 'victory-core/lib/victory-util/immutable.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/immutable'>;
}
declare module 'victory-core/lib/victory-util/label-helpers.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/label-helpers'>;
}
declare module 'victory-core/lib/victory-util/log.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/log'>;
}
declare module 'victory-core/lib/victory-util/prop-types.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/prop-types'>;
}
declare module 'victory-core/lib/victory-util/scale.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/scale'>;
}
declare module 'victory-core/lib/victory-util/selection.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/selection'>;
}
declare module 'victory-core/lib/victory-util/style.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/style'>;
}
declare module 'victory-core/lib/victory-util/textsize.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/textsize'>;
}
declare module 'victory-core/lib/victory-util/timer.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/timer'>;
}
declare module 'victory-core/lib/victory-util/transitions.js' {
  declare module.exports: $Exports<'victory-core/lib/victory-util/transitions'>;
}
declare module 'victory-core/src/index.js' {
  declare module.exports: $Exports<'victory-core/src/index'>;
}
declare module 'victory-core/src/victory-animation/util.js' {
  declare module.exports: $Exports<'victory-core/src/victory-animation/util'>;
}
declare module 'victory-core/src/victory-animation/victory-animation.js' {
  declare module.exports: $Exports<'victory-core/src/victory-animation/victory-animation'>;
}
declare module 'victory-core/src/victory-clip-container/victory-clip-container.js' {
  declare module.exports: $Exports<'victory-core/src/victory-clip-container/victory-clip-container'>;
}
declare module 'victory-core/src/victory-container/victory-container.js' {
  declare module.exports: $Exports<'victory-core/src/victory-container/victory-container'>;
}
declare module 'victory-core/src/victory-label/victory-label.js' {
  declare module.exports: $Exports<'victory-core/src/victory-label/victory-label'>;
}
declare module 'victory-core/src/victory-legend/helper-methods.js' {
  declare module.exports: $Exports<'victory-core/src/victory-legend/helper-methods'>;
}
declare module 'victory-core/src/victory-legend/victory-legend.js' {
  declare module.exports: $Exports<'victory-core/src/victory-legend/victory-legend'>;
}
declare module 'victory-core/src/victory-portal/portal.js' {
  declare module.exports: $Exports<'victory-core/src/victory-portal/portal'>;
}
declare module 'victory-core/src/victory-portal/victory-portal.js' {
  declare module.exports: $Exports<'victory-core/src/victory-portal/victory-portal'>;
}
declare module 'victory-core/src/victory-primitives/arc.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/arc'>;
}
declare module 'victory-core/src/victory-primitives/area.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/area'>;
}
declare module 'victory-core/src/victory-primitives/axis.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/axis'>;
}
declare module 'victory-core/src/victory-primitives/bar.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/bar'>;
}
declare module 'victory-core/src/victory-primitives/border.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/border'>;
}
declare module 'victory-core/src/victory-primitives/candle.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/candle'>;
}
declare module 'victory-core/src/victory-primitives/circle.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/circle'>;
}
declare module 'victory-core/src/victory-primitives/clip-path.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/clip-path'>;
}
declare module 'victory-core/src/victory-primitives/common-props.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/common-props'>;
}
declare module 'victory-core/src/victory-primitives/curve.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/curve'>;
}
declare module 'victory-core/src/victory-primitives/error-bar.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/error-bar'>;
}
declare module 'victory-core/src/victory-primitives/flyout.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/flyout'>;
}
declare module 'victory-core/src/victory-primitives/helpers.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/helpers'>;
}
declare module 'victory-core/src/victory-primitives/line.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/line'>;
}
declare module 'victory-core/src/victory-primitives/path-helpers.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/path-helpers'>;
}
declare module 'victory-core/src/victory-primitives/path.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/path'>;
}
declare module 'victory-core/src/victory-primitives/point.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/point'>;
}
declare module 'victory-core/src/victory-primitives/rect.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/rect'>;
}
declare module 'victory-core/src/victory-primitives/slice.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/slice'>;
}
declare module 'victory-core/src/victory-primitives/text.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/text'>;
}
declare module 'victory-core/src/victory-primitives/tspan.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/tspan'>;
}
declare module 'victory-core/src/victory-primitives/voronoi.js' {
  declare module.exports: $Exports<'victory-core/src/victory-primitives/voronoi'>;
}
declare module 'victory-core/src/victory-shared-events/victory-shared-events.js' {
  declare module.exports: $Exports<'victory-core/src/victory-shared-events/victory-shared-events'>;
}
declare module 'victory-core/src/victory-theme/grayscale.js' {
  declare module.exports: $Exports<'victory-core/src/victory-theme/grayscale'>;
}
declare module 'victory-core/src/victory-theme/material.js' {
  declare module.exports: $Exports<'victory-core/src/victory-theme/material'>;
}
declare module 'victory-core/src/victory-theme/victory-theme.js' {
  declare module.exports: $Exports<'victory-core/src/victory-theme/victory-theme'>;
}
declare module 'victory-core/src/victory-tooltip/victory-tooltip.js' {
  declare module.exports: $Exports<'victory-core/src/victory-tooltip/victory-tooltip'>;
}
declare module 'victory-core/src/victory-transition/victory-transition.js' {
  declare module.exports: $Exports<'victory-core/src/victory-transition/victory-transition'>;
}
declare module 'victory-core/src/victory-util/add-events.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/add-events'>;
}
declare module 'victory-core/src/victory-util/collection.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/collection'>;
}
declare module 'victory-core/src/victory-util/data.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/data'>;
}
declare module 'victory-core/src/victory-util/default-transitions.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/default-transitions'>;
}
declare module 'victory-core/src/victory-util/domain.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/domain'>;
}
declare module 'victory-core/src/victory-util/events.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/events'>;
}
declare module 'victory-core/src/victory-util/helpers.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/helpers'>;
}
declare module 'victory-core/src/victory-util/immutable.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/immutable'>;
}
declare module 'victory-core/src/victory-util/label-helpers.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/label-helpers'>;
}
declare module 'victory-core/src/victory-util/log.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/log'>;
}
declare module 'victory-core/src/victory-util/prop-types.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/prop-types'>;
}
declare module 'victory-core/src/victory-util/scale.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/scale'>;
}
declare module 'victory-core/src/victory-util/selection.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/selection'>;
}
declare module 'victory-core/src/victory-util/style.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/style'>;
}
declare module 'victory-core/src/victory-util/textsize.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/textsize'>;
}
declare module 'victory-core/src/victory-util/timer.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/timer'>;
}
declare module 'victory-core/src/victory-util/transitions.js' {
  declare module.exports: $Exports<'victory-core/src/victory-util/transitions'>;
}
